Repository FarPostBooks/farpostbooks_backend, pull requests merged in 2023-02, with the labels that each got.

#7 Fix admin views
  farpostbooks_backend/web/api/admin/views.py
Labels: bug

#9 🔖 Release version 1.0
  .flake8
  .github/auto-assign.yml
  .github/workflows/auto-assign.yml
  .github/workflows/tests.yml
  .gitignore
  README.md
  farpostbooks_backend/conftest.py
  farpostbooks_backend/db/dao/book_dao.py
  farpostbooks_backend/db/dao/user_dao.py
  farpostbooks_backend/db/dao/userbook_dao.py
  farpostbooks_backend/db/migrations/models/0_20230216175332_init.py
  farpostbooks_backend/db/models/book_model.py
  farpostbooks_backend/db/models/user_model.py
  farpostbooks_backend/db/models/userbook_model.py
  farpostbooks_backend/services/access_token.py
  farpostbooks_backend/services/search_book.py
  farpostbooks_backend/services/telegram_hash.py
  farpostbooks_backend/settings.py
  farpostbooks_backend/tests/test_admin.py
  farpostbooks_backend/tests/test_book.py
  farpostbooks_backend/tests/test_user.py
  farpostbooks_backend/tests/test_userbook.py
  farpostbooks_backend/web/api/admin/__init__.py
  farpostbooks_backend/web/api/admin/views.py
  farpostbooks_backend/web/api/book/__init__.py
  farpostbooks_backend/web/api/book/views.py
  farpostbooks_backend/web/api/router.py
  farpostbooks_backend/web/api/schema.py
  farpostbooks_backend/web/api/user/schema.py
  farpostbooks_backend/web/api/user/views.py
  farpostbooks_backend/web/api/userbook/__init__.py
  farpostbooks_backend/web/api/userbook/schema.py
  farpostbooks_backend/web/api/userbook/views.py
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#11 Added metrics / Deleted old logging with loguru + sentry
  .flake8
  .github/auto-assign.yml
  .github/workflows/auto-assign.yml
  README.md
  deploy/docker-compose.yml
  etc/dashboards.yaml
  etc/dashboards/fastapi-observability.json
  etc/grafana/datasource.yml
  etc/prometheus/prometheus.yml
  farpostbooks_backend/__main__.py
  farpostbooks_backend/conftest.py
  farpostbooks_backend/db/dao/userbook_dao.py
  farpostbooks_backend/logging.py
  farpostbooks_backend/services/search_book.py
  farpostbooks_backend/services/utils.py
  farpostbooks_backend/settings.py
  farpostbooks_backend/web/application.py
  farpostbooks_backend/web/lifetime.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#12 Notifications to telegram
  .flake8
  .gitignore
  deploy/docker-compose.yml
  farpostbooks_backend/__main__.py
  farpostbooks_backend/db/dao/book_dao.py
  farpostbooks_backend/db/dao/user_dao.py
  farpostbooks_backend/services/scheduler.py
  farpostbooks_backend/services/search_book.py
  farpostbooks_backend/settings.py
  farpostbooks_backend/web/application.py
  poetry.lock
  pyproject.toml
Labels: enhancement
